export { default as Acquisti } from './acquisti'
export { default as Anagrafica } from './anagrafica'
export { default as Corrispettivi } from './corrispettivi'
export { default as Documenti } from './documenti'
export { default as Info } from './info'
export { default as Magazzino } from './magazzino'
export { default as Mail } from './mail'
export { default as Prodotti } from './prodotti'
